### ISSUE TITLE
FadeHover and Rounded Box

### ISSUE THREAD

**Issue by RadioactvePixels** [Threebow/tdlib#10]
If there is a button with FadeHover near the edge of a panel with rounded corners, the fade part will clip outside of the boundaries. 
http://radioactve.cf/img/HPqwE

**Comment by dgrishaev1** [comment]
I don't think this is relevant, but it may be useful to someone:
Just add num of corner radius to third argument of :FadeHover
```
		:Background(rp.col.Red, 8)	
		:FadeHover(Color(255,255,255,15), 1, 8)
```

**Comment by RadioactvePixels** [comment]
Oh, yes this helps very much still. Thank you!
