### ISSUE TITLE
CircleClick

### ISSUE THREAD

**Issue by Srlion** [Threebow/tdlib#3]
Hey, CircleClick doesn't work if the DoClick function gonna remove it's parent or itself, tried to use SetRemove but didn't work too.
 Edit: It does work if use a timer.

**Comment by Threebow** [comment]
That's to be expected, a click effect obviously will not be shown if the button is removed the second it is clicked

**Comment by Srlion** [comment]
Why don't u use panel.Depressed in paint function? it will make it work without any timer

**Comment by Threebow** [comment]
There's no point though if the panel is going to be removed on click
