### ISSUE TITLE
Breaks Blogs

### ISSUE THREAD

**Issue by Srlion** [Threebow/tdlib#4]
Hey, just noticed that this breaks Blogs, that's the error i get: 

> [ERROR] addons/_blogs-remastered-12/lua/vgui/blogs.lua:257: attempt to concatenate field 'Text' (a function value)
>   1. UpdateTextObj - addons/_blogs-remastered-12/lua/vgui/blogs.lua:257
>    2. unknown - addons/_blogs-remastered-12/lua/vgui/blogs.lua:250
>

**Comment by Threebow** [comment]
Blogs overwrites a panels .Text field somewhere

**Comment by Srlion** [comment]
So should i contact billy to add support for this addon or what?

**Comment by Threebow** [comment]
I will fix this myself but it will need you to initialize your panels with a different constructor

**Comment by Srlion** [comment]
Okay, will just wait

**Comment by Srlion** [comment]
any news? been 4 days :c

**Comment by Threebow** [comment]
shiit forgot to add this to my todo list i'll get on it after my finals

**Comment by Threebow** [comment]
the problem is that derma panels will have to be initialized anew, or you'll have to call a metafunction on all panels you use TDLib on, i'll add both options

**Comment by Threebow** [comment]
Fixed in latest version, update guide is [here](https://threebow.gitbooks.io/tdlib/content/updating.html)

**Comment by Srlion** [comment]
Thanks dude <3
